### ISSUE TITLE
Option for setting ELB arn is no longer available?

### ISSUE THREAD

**Issue by fedepazos95** [boltops-tools/ufo#163]
Hi! I'm trying to upgrade to the newest version due to the improvements but I can't find how to set the ELB arn like in the previous versions using the --elb flag

This option is no longer available?
I would like to use it because I have several services that uses the same ALB and I can't find a workaround because ECS won't allow to change load balancing settings after creation of the service

**Comment by tongueroo** [comment]
Handled by #166. Please community forums for questions. Thanks.
