### ISSUE TITLE
Service auto scaling properties

### ISSUE THREAD

**Issue by MaartenDCrius** [boltops-tools/ufo#64]
I would like to setup autoscaling policies for the cluster/service in ecs during the ufo deploy.

Example:

Scale up   tasks and or EC2 instances if CPUUtilization exceeds 75%

**Comment by tongueroo** [comment]
Yup. Wanted to do this but haven't had the time. Happy to consider PRs for this.

**Comment by tongueroo** [comment]
Done as a part of 6.0 #125
