### ISSUE TITLE
configuring number of healthy containers?

### ISSUE THREAD

**Issue by mepatterson** [boltops-tools/ufo#66]
Would love to be able to configure the `minimumHealthyPercent` (and maximum too) on per-service basis. Is this possible anywhere in the ufo config?

**Comment by tongueroo** [comment]
Currently, not possible to do this on a per-service basis. 

You can do set it across all services by customizing the generated CloudFormation ECS resource. This might help:

* [UFO Customizing Resources docs](http://ufoships.com/docs/settings-cfn/)
* #65 Another  person had a similar need and ended up customizing resources
* [CloudFormation AWS::ECS::Service Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-deploymentconfiguration) Looks like need to add a `DeploymentConfiguration` setting

Am happy to consider PRs for this. One note, think it would be good if it looks up the current values of minimumHealthyPercent and MaximumPercent so users do not have to type it in repeatedly in the future.

**Comment by tongueroo** [comment]
Resolved by #126 

Docs: 

* https://ufoships.com/docs/config/cluster/
* https://ufoships.com/docs/debug/deployment-configuration/
